### ISSUE TITLE
[BUG] Notifications crash

### ISSUE THREAD

**Issue by Its3rr0rsWRLD** [RusherDevelopment/rusherhack-issues#1659]
**Describe the bug**
The client crashes when enabling phase without pearls

**To Reproduce**
Enable phase without pearls

```
[01:22:44] [Render thread/ERROR]:
 [Phase] You have no pearls in your hotbar!
[01:22:44] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_32124(class_638.java:260) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2011) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.util.NoSuchElementException
	at java.util.ArrayDeque.getLast(Unknown Source) ~[?:?]
	at net.minecraft.class_4587.method_23760(class_4587.java:71) ~[client-intermediary.jar:?]
	at org.rusherhack.?.?(?.java:589) ~[?:?]
	at org.rusherhack.�.getStringWidth(�.java:267) ~[?:?]
	at org.rusherhack.�.?(�.java:164) ~[?:?]
```

**Comment by FluorideHistorian** [comment]
i am unable to reproduce and this crash log doesn't appear to have anything to do with phase
